#name, main, version and api are required
name: TagManager
main: milk.nametagtingText
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0"
api: ["1.0.0"]

load: STARTUP
author: SW-Team
description: 텍스트를 띄웁니다
website: https://github.com/SW-Team/TagManager
commands:
  tag:
    description: 텍스트를 띄웁니다
    permission: tagmanager.command.tag
    usage: "사용법: /tag <text> (<x> <y> <z> <level>)"
permissions:
  tagmanager.command.tag:
    default: op
    description: ""